apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-and-push-homeoffice-backend-run
  namespace: quarkusdroneshop-cicd
  labels:
    app.kubernetes.io/name: homeoffice-backend
spec:
  pipelineRef:
    name: build-and-push-homeoffice-backend
  params:
    - name: image-tag
      value: latest
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 2Gi
    - name: maven-cache
      persistentVolumeClaim:
        claimName: maven-cache-pvc
