{
  "type": "record",
  "name": "record",
  "namespace": "org.apache.flink.avro.generated",
  "fields": [
    { "name": "eventId", "type": ["null", "string"], "default": null },
    { "name": "orderId", "type": ["null", "string"], "default": null },
    { "name": "eventType", "type": ["null", "string"], "default": null },
    { "name": "eventTimestamp", "type": ["null", { "type": "long", "logicalType": "timestamp-millis" }], "default": null },
    { "name": "orderSource", "type": ["null", "string"], "default": null },
    { "name": "location", "type": ["null", "string"], "default": null },
    { "name": "loyaltyMemberId", "type": ["null", "string"], "default": null },
    { "name": "orderStatus", "type": ["null", "string"], "default": null },
    {
      "name": "lineItem",
      "type": ["null", {
        "type": "record",
        "name": "record_lineItem",
        "fields": [
          { "name": "itemId", "type": ["null", "string"], "default": null },
          { "name": "item", "type": ["null", "string"], "default": null },
          { "name": "name", "type": ["null", "string"], "default": null },
          { "name": "price", "type": ["null", { "type": "bytes", "logicalType": "decimal", "precision": 10, "scale": 2 }], "default": null },
          { "name": "lineItemStatus", "type": ["null", "string"], "default": null },
          { "name": "assemblyLine", "type": ["null", "string"], "default": null },
          { "name": "madeBy", "type": ["null", "string"], "default": null }
        ]
      }],
      "default": null
    },
    { "name": "sourceDomain", "type": ["null", "string"], "default": null },
    { "name": "sourceTopic", "type": ["null", "string"], "default": null }
  ]
}
